apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "business-web.name" . }}-env
  labels:
    {{- include "business-web.labels" . | nindent 4 }}
data:
  env.json: |
    {{ .Values.env | toJson }}
